name: siapbayar
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter_native_splash: ^2.4.6
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logosplash.png
  
  fonts:
    - family: Pacifico
      fonts:
      - asset: fonts/Pacifico.ttf


flutter_native_splash:
  color: '#ffffff'
  android: true
  ios: true